md jar_dependency
md jar_dependency\src
md jar_dependency\src\main
md jar_dependency\src\main\java
md jar_dependency\src\main\java\com
md jar_dependency\src\main\java\com\example
md jar_dependency\src\test
md jar_dependency\src\test\java
md src
md src\main
md src\main\java
md src\main\java\com
md src\main\java\com\example2
md src\main\resources
md src\main\webapp
md src\main\webapp\WEB-INF
md src\main\webapp\jsp
md src\test
md src\test\java
