mkdir jar_dependency
mkdir jar_dependency/src
mkdir jar_dependency/src/main
mkdir jar_dependency/src/main/java
mkdir jar_dependency/src/main/java/com
mkdir jar_dependency/src/main/java/com/example
mkdir jar_dependency/src/test
mkdir jar_dependency/src/test/java
mkdir src
mkdir src/main
mkdir src/main/java
mkdir src/main/java/com
mkdir src/main/java/com/example2
mkdir src/main/resources
mkdir src/main/webapp
mkdir src/main/webapp/WEB-INF
mkdir src/main/webapp/jsp
mkdir src/test
mkdir src/test/java
